language: python

python:
  - "2.7"

sudo: required

before_install:
  - cd $TRAVIS_BUILD_DIR/vendor
  - tar -xzvf EXASolution_SDK-5.0.17.tar.gz
  - cd $TRAVIS_BUILD_DIR/vendor/EXASolution_SDK-5.0.17/Python/
  - python setup.py install
  - cd $TRAVIS_BUILD_DIR/vendor
  - tar -xzvf Tableau-SDK-Python-Linux-64Bit-10-1-4.tar.gz
  - cd $TRAVIS_BUILD_DIR/vendor/Tableau*/
  - python setup.py install
  - cd $TRAVIS_BUILD_DIR
  - sudo apt-get install unixodbc-dev
  - sudo apt-get install python-pyodbc

install:
  - pip install -r $TRAVIS_BUILD_DIR/requirements.txt

script:
  - nosetests
